const TYPES = {
    SET_LOADING: 'SET_LOADING',
    SET_STATES: 'SET_STATES',
    CLEAR_STATES: 'CLEAR_STATES',
    SET_PROJECT_BRIEFS: 'SET_PROJECT_BRIEFS',
    SET_DOCUMENT_GROUPS: 'SET_DOCUMENT_GROUPS'
};

export default TYPES;
